### ISSUE TITLE
Ng Serve Produces - Error: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by lenichols** [ngneat/spectator#285]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
running ng serve on angular 8.3.5 produces an error:

ERROR in node_modules/@ngneat/spectator/lib/base/dom-spectator.d.ts:58:9 - error TS1086: An accessor cannot be declared in an ambient context.

![Screen Shot 2020-03-03 at 10 54 34 AM](https://user-images.githubusercontent.com/5247113/75809549-ce139700-5d3d-11ea-9b33-6edd2ae279b8.png)

## Expected behavior
ng serve should run the application

## What is the motivation / use case for changing the behavior?
Running

>  npm test

 runs fine but `ng serve` produces the error

## Environment

<pre><code>
Angular version: 8.3.5

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.1  
- Platform:  Mac

Others:
Uninstalled and re-installed spectator and application still produces these errors when ran.
</code></pre>

**Comment by NetanelBasal** [comment]
Why ng serve runs Spectator? Something doesn't make sense here.

**Comment by seangwright** [comment]
I see this error when I run `npm test`

```json
"@angular/core": "8.2.6",
"@ngneat/spectator": "^5.3.1",
```

I think it's caused by using 5.x of Spectator with Angular 8.x.

When I changed the Spectator version to 4.11.1 (the last version before Angular 9 support was added), everything worked fine!

**Comment by DanielKlier** [comment]
I'm also seeing the same errors as @seangwright get when running the tests. I just upgraded a project from v3 to v5 and downgraded to v4.
I think this is related to the version of TypeScript being used. After upgrading to Angular 8, we got TypeScript 3.5. I haven't tried a newer version with Angular 8, yet.

**Comment by NetanelBasal** [comment]
V5 should be compatible with ViewEngine.

**Comment by NetanelBasal** [comment]
https://github.com/microsoft/TypeScript/issues/36207

**Comment by rygar08** [comment]
I'm also seeing this error. I've tried different versions of typescript. My project uses angular 7.1.2 and I'm currently using typescript 3.1.1.

ERROR in node_modules/@ngneat/spectator/lib/base/dom-spectator.d.ts(59,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/spectator/lib/base/dom-spectator.d.ts(66,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by NetanelBasal** [comment]
@rygar08 it's not about your TS version. It's the Spectator version.

**Comment by NetanelBasal** [comment]
Upgrade to TS 3.7+

**Comment by rygar08** [comment]
I upgrade to 3.7.5, still had the error. I ended up migrating from angular 7 to 9 which fixed the issue.

**Comment by NetanelBasal** [comment]
Should work with v5.10.0
